First PullRequest
Valdemarushka/java-filmorate pull request #1
Opened 2022-08-06 11:08 UTC by Valdemarushka

пробуем

2022-08-07 07:57 UTC, chewmag requested changes
Приветствую Владимир!

Вся требуемая функциональность реализована :) В качестве предложения по улучшениям можно рассмотреть реализацию дополнительного задания, поэтому отправлю текущую итерацию на доработку :)

2022-08-07 07:57 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(FilmController.class);
В проекте подключен lombok, можно использовать его инструментарий для подключения логирования https://howtodoinjava.com/spring-boot2/logging/logging-with-lombok/
Аналогично для UserController.

2022-08-07 07:57 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/tools/ModelTools.java
> +    //методы для фильмов
Комментарий живет сам по себе, оторван от всего остального :)

2022-08-07 07:57 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/tools/ModelTools.java
> +public class ModelTools {
Вся валидация, которая делается в методе, может быть упрощена при использовании spring-boot-starter-validation, это предложения по дополнительному заданию :)

2022-08-07 07:57 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/tools/ModelTools.java
> +        final LocalDate MIN_RELEASE_DATE = LocalDate.of(1895, 11, 28);
Дату в константу :)

2022-08-10 06:58 UTC, Valdemarushka commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final static Logger log = LoggerFactory.getLogger(FilmController.class);
Исправлено)

2022-08-10 06:59 UTC, Valdemarushka commented on src/main/java/ru/yandex/practicum/filmorate/tools/ModelTools.java
> +    //методы для фильмов
Исправлено)

2022-08-10 07:00 UTC, Valdemarushka commented on src/main/java/ru/yandex/practicum/filmorate/tools/ModelTools.java
> +public class ModelTools {
Если это не обязательно, то я пожалуй пока воздержусь. просто времени на погружение в дополнительные темы нет совсем. и так с прошлым спринтом чуть не развелся)

2022-08-10 07:00 UTC, Valdemarushka commented on src/main/java/ru/yandex/practicum/filmorate/tools/ModelTools.java
> +        final LocalDate MIN_RELEASE_DATE = LocalDate.of(1895, 11, 28);
Исрпавлено)

2022-08-10 08:41 UTC, Valdemarushka commented
Извиняюсь, отправил на проверку и решил доделать. но все пошло через одно место. пытаюсь исправить. Не могу понять как тесты junit обновить, что бы проходили проверки.

2022-08-10 08:51 UTC, Valdemarushka commented
Мне сказали что тесты нужны только на кастомные валидации. Оставил только их. Не знаю, верно ли.

2022-08-10 19:31 UTC, chewmag requested changes
Приветствую Владимир! 
Поскольку всю валидацию в  spring-boot-starter-validation поместить не удалось, лучше оставить все как было.

2022-08-12 19:28 UTC, chewmag approved these changes
Теперь порядок, остановимся на этом варианте.

2022-08-13 03:21 UTC, merged