Add friends likes
Valdemarushka/java-filmorate pull request #2
Opened 2022-08-24 04:37 UTC by Valdemarushka

2022-08-24 19:10 UTC, chewmag requested changes
Приветствую Владимир!

Доработки не требуются. Предлагаю подумать над реализацией улучшений:

- Работать с пользователями и фильмами только через сервисы. Все необходимые зависимости в сервисах есть;
- убрать public из интерфейсов;
- инициализировать необходимые коллекции в моделях при объявлении, чтобы избежать многократных проверок на null.

2022-08-24 19:10 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return inMemoryUserStorage.getAllUser();
Здесь также, предлагаю вынести все функции по управлению пользователями в UserService.

2022-08-24 19:10 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            return new HashSet<>();
Лучше заиницализировать тогда здесь коллекцию, раз уж она ленивая.

2022-08-24 19:10 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Аннотацию оторвало от метода :)

2022-08-24 19:10 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getLikes() == null) {
Чтобы подобными вещами не страдать, проще сразу проинициализировать коллекцию при объявлении в моделях Film, User.

2022-08-24 19:10 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Film createFilm(Film film);
Спецификаторы public в интерфейсах избыточны

2022-08-24 19:10 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    public User createUser(User user);
Спецификаторы public в интерфейсах избыточны :)

2022-08-25 08:12 UTC, Valdemarushka commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            return new HashSet<>();
Тут пока не могу разобраться. ставлю в  Film
`private Set<Integer> likes = new HashSet<>();`
 и после этого проверки на получение популярных фильмов выдают 500ую ошибку, так как в одном из фильмов как то оказывается likes = null. Если направите, то исправлю)

2022-08-25 18:35 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            return new HashSet<>();
Сходу не подскажу, надо дебажить. Оставим пока как есть тогда, раз тесты проходят.

2022-08-25 18:37 UTC, chewmag approved these changes
Приветствую Владимир!

Можно переносить изменения в main, проблему с инициализацией коллекции likes оставим на потом :)

2022-08-26 03:33 UTC, merged